# Generated by Django 4.0.4 on 2022-07-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='countInStockM',
        ),
        migrations.AddField(
            model_name='product',
            name='countInStockQ',
            field=models.IntegerField(default=0),
        ),
    ]
