# Generated by Django 4.0.4 on 2022-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_shippingaddress_review_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
    ]
