# Generated by Django 4.0.4 on 2022-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_payment_userprofile_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_info',
            name='building',
            field=models.CharField(max_length=100),
        ),
    ]
