# Generated by Django 4.0.4 on 2022-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_info_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(blank=True, max_length=250)),
                ('alert', models.CharField(choices=[('alert-danger', 'alert-danger'), ('alert-warning', 'alert-warning'), ('alert-light', 'alert-light'), ('alert-secondary', 'alert-secondary'), ('alert-success', 'alert-success')], max_length=100)),
                ('support_link', models.URLField(blank=True)),
            ],
        ),
    ]
