# Generated by Django 4.0.4 on 2022-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='alert',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=100),
        ),
    ]
