# Generated by Django 4.0.4 on 2022-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_announcement_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='change',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='room_info',
            name='cell_number',
            field=models.CharField(max_length=512),
        ),
    ]
