import image1 from "./images/Albany-Superior_1.png";
const products = [
  {
    _id: "1",
    name: "Go Slo",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 89.99,
    countInStock: 10,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
  {
    _id: "2",
    name: "Chocolate",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 89.99,
    countInStock: 10,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
  {
    _id: "3",
    name: "Go Slo Peri",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 89.99,
    countInStock: 10,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
  {
    _id: "4",
    name: "Stylos",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 6,
    countInStock: 0,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
  {
    _id: "5",
    name: "Doritos",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 89.99,
    countInStock: 10,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
  {
    _id: "6",
    name: "Albany Bread",
    image: image1,
    quantity: "per item",
    brand: "Truda",
    //   'category': 'Electronics',
    price: 89.99,
    countInStock: 10,
    //   'rating': 4.5,
    //   'numReviews': 12,
  },
];

export default products;
